// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeIwuLetDEoDzA8866Bu97KTHfvHQEIeo',
    appId: '1:792593901522:web:73fb8ec40d47f408968a0b',
    messagingSenderId: '792593901522',
    projectId: 'ecommerce-9a611',
    authDomain: 'ecommerce-9a611.firebaseapp.com',
    storageBucket: 'ecommerce-9a611.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAElbmsLmlB_l1lW5zVbzuqkXMNxXmmG5U',
    appId: '1:792593901522:android:cd230d44164c1ced968a0b',
    messagingSenderId: '792593901522',
    projectId: 'ecommerce-9a611',
    storageBucket: 'ecommerce-9a611.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJyierRq46NemucgOEvDAh-YMchmq_fDU',
    appId: '1:792593901522:ios:7b8b5a8838f6a130968a0b',
    messagingSenderId: '792593901522',
    projectId: 'ecommerce-9a611',
    storageBucket: 'ecommerce-9a611.appspot.com',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJyierRq46NemucgOEvDAh-YMchmq_fDU',
    appId: '1:792593901522:ios:d518b2de9697ea08968a0b',
    messagingSenderId: '792593901522',
    projectId: 'ecommerce-9a611',
    storageBucket: 'ecommerce-9a611.appspot.com',
    iosBundleId: 'com.example.storeApp.RunnerTests',
  );
}
